server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${system.datasource.driver-class-name}
      url: jdbc:mysql://${system.datasource.host}:${system.datasource.port}/${system.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${system.datasource.username}
      password: ${system.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.system.entity
  type-handlers-package: com.system.handler
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    com:
      system:
        mapper: debug
        service: info
        controller: info

system:
  jwt:
    secret-key: your-secret-key
    ttl: 7200000  # 2小时
    # 管理端
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: leaf
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: autumn
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
